### ISSUE TITLE
Incorrect Mass?

### ISSUE THREAD

**Issue by thebeardphantom** [ProjectBorealis/PBCharacterMovement#1]
I’m not super familiar with UE4, but in your movement code you specify Gordon’s weight as such:

`Mass = 65.77f; // Gordon is 145lbs`

Except that’s not weight, it’s mass. Since weight is `mass • gravity` that would make Gordon 1431 lbs, assuming that you’re using UE4’s default earth gravity of 9.87.

**Comment by mastercoms** [comment]
Weight in metric units is Newtons, not kilograms. The conversion was made from pounds to kilograms, so the inverse would still have the same result, not 1431lbs.
