### ISSUE TITLE
Can't compile using UE 4.24

### ISSUE THREAD

**Issue by olivatooo** [ProjectBorealis/PBCharacterMovement#11]

**Comment by mastercoms** [comment]
We'll be releasing a new version for 4.24 soon.

**Comment by l0m-dev** [comment]
Any news on the newer version?

**Comment by mastercoms** [comment]
Hi, sorry for the long wait but we've been pretty busy on prioritized high level tasks so it'll still be a while longer. But not all bad news! As part of that effort, we've been able to make some important improvements to movement!

**Comment by Zenahr** [comment]
It does compile on my engine (v.4.24) Just make sure to paste the plugin into the project folder (not your engine plugins directory) and  re-build your project manually i.e. with Visual Studio 2017.

**Comment by damonflavell** [comment]
Can't wait.

**Comment by damonflavell** [comment]
Can confirm compiling manually works.

**Comment by mastercoms** [comment]
This one has been fixed, moving over to #15
