### ISSUE TITLE
Unable to Compile on 4.22.3 build

### ISSUE THREAD

**Issue by amuDev** [ProjectBorealis/PBCharacterMovement#12]
After putting the project in the /Plugins/ and restarting the project UE4 lets me know it was built with a different engine version and needs to be recompiled, I allow the engine to recompile on its own and it errors out, telling me to build from source. The build from source also errors out, full logs attached.
[UBT-UE4Editor-Win64-Development.txt](https://github.com/ProjectBorealis/PBCharacterMovement/files/4265262/UBT-UE4Editor-Win64-Development.txt)

**Comment by mastercoms** [comment]
In the log, you'll be able to find the compile errors that you need to fix for your UE4 version.
