### ISSUE TITLE
Is it possible to to disable accelerated back hopping?

### ISSUE THREAD

**Issue by labratsoftworks** [ProjectBorealis/PBCharacterMovement#2]
I'm working on a multiplayer project and I was wondering if there were ways of curtailing bhopping (specifically ABH) given how overpowered that would be in a multiplayer setting. Thanks so much, this project is amazing!

**Comment by mastercoms** [comment]
Just remove this part: https://github.com/ProjectBorealis/PBCharacterMovement/blob/a7ad8fcf2b85a01162f2ec18ec3cabf93fa9278e//Source/PBCharacterMovement/Private/Character/PBPlayerCharacter.cpp#L98-L147

**Comment by mastercoms** [comment]
I've published an untested no-abh branch. This removed the ABH backwards boost. https://github.com/ProjectBorealis/PBCharacterMovement/tree/no-abh
