### ISSUE TITLE
Surfing

### ISSUE THREAD

**Issue by SirVoRaK** [ProjectBorealis/PBCharacterMovement#23]
How can I use the surfing feature? I tried with just a box rotated in 45 degrees but didn't work.

**Comment by mastercoms** [comment]
You need to add WIP_SURFING to PublicDefinitions.

**Comment by SirVoRaK** [comment]
So in the PBPlayerMovement.h I need to add to public the:
#if WIP_SURFING
	void PreemptCollision(float DeltaTime, float SurfaceFriction);
#endif
?
And to use is just put a cube rotated in 45 degrees?

**Comment by MartinWessel96** [comment]
Hey sorry if I am Stupid but could you explain how to get this to working?
I try to add WIP_SURFINGt to PublicDefinitions but maybe i am doing somthing wrong because its just not working at all.

**Comment by mastercoms** [comment]
If it is of interest, we have finally published our full surfing code to the repo, and no extra configuration is needed. (besides maybe setting AirAccelerationMultiplier to 100 or 1000, like how surf servers set it with sv_airaccelerate)
