### ISSUE TITLE
version 1.0.6

### ISSUE THREAD

**Issue by srun142** [ProjectBorealis/PBCharacterMovement#24]
Not sure why, but the plugin doesn't want to start. unreal version 4.26.1. I threw it as it should in Plugins / in my project
![Desktop Screenshot 2021 03 24 - 22 53 49 08](https://user-images.githubusercontent.com/44543555/112341257-d8f7eb80-8cf3-11eb-9c69-a1cf2d336311.png)

**Comment by Ratchet7x5** [comment]
You may want to try building from source. So open your .sln file and build/rebuild. 

Let me know if this fixes it.

**Comment by srun142** [comment]
If I knew how to do it :(
