### ISSUE TITLE
Packaged project cannot be opened (failed to load module PBCharacterMovement)

### ISSUE THREAD

**Issue by Zenahr** [ProjectBorealis/PBCharacterMovement#27]
Everything works fine in-editor. Packaging the project up also works fine with the plugin active. Trying to run the packaged executable is the only thing that fails with following message: 

![image](https://user-images.githubusercontent.com/47085752/179118046-942b602f-cb6b-41f9-880f-fa2ebbcb5aea.png)

**Comment by Zenahr** [comment]
Engine version tested with: 5.0.1

**Comment by Zenahr** [comment]
@mastercoms any clue?

**Comment by mastercoms** [comment]
You need to use a C++ project, see #5
