### ISSUE TITLE
Cannot interact with physics enabled actors 

### ISSUE THREAD

**Issue by Veathen** [ProjectBorealis/PBCharacterMovement#28]
video: of issue https://www.youtube.com/watch?v=YG58aXPaSKI

Don't know if this is a issue per say or i've missed something blatantly obvious and this should've gone in the discord instead.

Note: physics interactions work fine with the third person template character

**Comment by mastercoms** [comment]
enable physics interactions in the character movement component

**Comment by Veathen** [comment]
Physics interactions was on by default. 

![image](https://user-images.githubusercontent.com/28810479/182011726-a255875b-79ff-4f1a-b36b-f521bb88fa74.png)
At square one.
