### ISSUE TITLE
How should we edit and recompile the plugin for custom modifications?

### ISSUE THREAD

**Issue by labratsoftworks** [ProjectBorealis/PBCharacterMovement#3]
There doesn't appear to be much documentation on plugin editing and when I asked around I received mixed responses. My guess is that other plugins handle to process differently?  What step by step process is required to edit the source code and recompile the plugin?

**Comment by mastercoms** [comment]
Edit the source, delete the Binaries folder and launch your project.. Press yes when prompted to compile PBCharacterMovement.
