### ISSUE TITLE
How to setup in UE5

### ISSUE THREAD

**Issue by b3326023** [ProjectBorealis/PBCharacterMovement#30]
Excuse me, I'm not familiar with UE, could you please detail the following steps?

1. Create a new player controller in Blueprint or C++. Here's a [simple Blueprint example](https://blueprintue.com/blueprint/l7vxktwk/).
2. Create a Blueprint child class of PBPlayerCharacter.
3. Create a gamemode with Default Pawn set to your Blueprint character class, and Player Controller set to your player controller.

I don't know how to execute these steps in UE, please help me 🙏🙏
Really appreciate!!

**Comment by mastercoms** [comment]
https://docs.unrealengine.com/5.0/en-US/setting-up-a-character-in-unreal-engine/#creatingaplayercontroller
