### ISSUE TITLE
AutoBhoping still happens when disabled(UE5)

### ISSUE THREAD

**Issue by AnthonyPython** [ProjectBorealis/PBCharacterMovement#31]
Even though Bhoping is disabled by default it still happens in UE5
Setup standard blueprint example.

**Comment by mastercoms** [comment]
Either auto bhop or move.Pogo set to 1 will cause it. So please set the console variable to 0.

**Comment by AnthonyPython** [comment]
I did not set it to 1

**Comment by ComputeSoar** [comment]
move.Pogo 0 :)
