### ISSUE TITLE
move.pogo is enabled by default in plugin

### ISSUE THREAD

**Issue by AnthonyPython** [ProjectBorealis/PBCharacterMovement#32]
is this intentional? it is set to 1 in the plugin code.

doesn't seem like it should be.

**Comment by mastercoms** [comment]
It's enabled by default to facilitate evaluation and testing of the plugin's features. It's easy enough to disable and I would say most users prefer it on in their initial usage.

**Comment by mastercoms** [comment]
In Config/DefaultEngine.ini:

```ini
[SystemSettings]
move.Pogo=0
```
