### ISSUE TITLE
Change UPBPlayerMovement properties

### ISSUE THREAD

**Issue by clankill3r** [ProjectBorealis/PBCharacterMovement#34]
Hi,

How can I change the properties in UPBPlayerMovement?
Like what kind of blueprint do I need to create?
(I prefer not to change the value in the PBPlayerMovement.cpp file).

This is one of the many things I tried:

![Screenshot_20221124_121157](https://user-images.githubusercontent.com/738650/203770530-ccc46fb2-8e1a-4be1-8fdb-7bb44f031eb3.png)

> 'PBPlayer Movement' does not inherit from 'Character' ( Cast To PBPlayerMovement  would always fail).

I understand the error, I just don't understand on where and how to use the `SET Air Acceleration Multiplier` Node.

**Comment by mastercoms** [comment]
In this Blueprint, you'd access Get Character Movement and then cast. But no need to even do that. You can change it in the defaults for the Blueprint too, just find the character movement component in your character blueprint's components:
![components]https://user-images.githubusercontent.com/2672245/203780004-dbdd8919-fca2-4046-9d03-ac5fc97a66f9.png)

Name might be different, but hopefully you get the idea.
