### ISSUE TITLE
PBMove Step Sound Objects do not get destroyed after finishing audio?

### ISSUE THREAD

**Issue by samthebest000** [ProjectBorealis/PBCharacterMovement#41]
I was playing around with the PBCharacterMovement class in UE5, I added some sounds, and I noticed whenever a step sound is played in test mode, the object counter increments, but never decrements after playing the sound, correct me if I am wrong but arent sound objects supposed to self destruct after finishing the audio?

**Comment by mastercoms** [comment]
If you can identify what exactly is being allocated through a mem report, then we could assist but there are no allocations beyond the sound spawning which is auto destroyed by the engine. PB Move Step sound objects are never allocated, they use the class default object. Keep in mind that GC does not constantly run so object counts may not reflect an object that will be deallocated depending on what you are looking at.

**Comment by samthebest000** [comment]
Ah I see, then there I probably nothing to worry about if it uses the default object, thanks for the info
