### ISSUE TITLE
We kindly request your assistance in implementing .t3d loading and processing for our project. This 3D format is essential for our open-source engine, reminiscent of the Unreal/Unreal Tournament era. Your expertise and support in this matter would be greatly appreciated.  Thank you for considering our plea, and we look forward to your valuable contribution.  (relevant files: model_brush.c, relevant function: void T3d_Attempt_Which_will_Mod_OBJ_Load(dp_model_t *mod, void *buffer, void *bufferend)

### ISSUE THREAD

**Issue by chaosesqueteam** [ProjectBorealis/PBCharacterMovement#43]
We kindly request your assistance in implementing .t3d loading and processing for our project. This 3D format is essential for our open-source engine, reminiscent of the Unreal/Unreal Tournament era. Your expertise and support in this matter would be greatly appreciated.

Thank you for considering our plea, and we look forward to your valuable contribution.

(relevant files: model_brush.c, relevant function: void T3d_Attempt_Which_will_Mod_OBJ_Load(dp_model_t *mod, void *buffer, void *bufferend)

**Comment by mastercoms** [comment]
Thanks for the request! Unfortunately, we have no plans to implement t3d support at this time.
