### ISSUE TITLE
5.2 no compile error but crash

### ISSUE THREAD

**Issue by RaphpowerUE4** [ProjectBorealis/PBCharacterMovement#46]
![image](https://github.com/ProjectBorealis/PBCharacterMovement/assets/51867537/f4d9b9ad-2cbb-4705-bb5b-296a85faf2b8)

![image](https://github.com/ProjectBorealis/PBCharacterMovement/assets/51867537/1ce8b4b7-01ec-4e81-8081-faf568efa4cc)

Is 5.2 support possible ?
I'm trying to fix it myself but I have basic c++ knowledge

**Comment by Kotyesz** [comment]
Make sure the engine is not running when compiling, cause that will say it works even if it doesn't. Maybe it managed to compile in a way that tries to read deleted memory before and is now stuck on that version. Try rebuilding the project from the solution while the engine is closed.

**Comment by RaphpowerUE4** [comment]
I didn't fixed it but I was dumb and I forgot to delete all derived data and build cache, it fixed everything, sorry and thanks for your time!
