### ISSUE TITLE
Add a version with Box Collision (Axis Aligned Bounding Box)

### ISSUE THREAD

**Issue by randomperson189** [ProjectBorealis/PBCharacterMovement#48]
Currently this uses Capsule Collision but it would also be nice to have a version with a Box Collider that doesn't rotate, much like actual HL2. Capsule Collision also has this problem where when I'm standing near the edge of a surface and jump, I end up sliding off it which can get annoying and would never happen in any Source Engine game.

**Comment by mastercoms** [comment]
We emulate a box collider already in all relevant cases, I'm not sure why you would be experiencing the slide off behavior
