### ISSUE TITLE
Works fine in editor, not after launching/packaging

### ISSUE THREAD

**Issue by axel37** [ProjectBorealis/PBCharacterMovement#5]
**Hello !**
First, I want to mention that I'm new to Unreal, and I'm posting here as a last resort because I could not solve this myself.
___
After following the instructions *(more or less)*, I managed to get this working... only in the editor.
When I launch or package the project, I get issues... So far, I've tried setting it up in 2 different ways *(it works fine in the editor either way)*.

- Using the *PBPlayerCharacter* as default pawn class : 
Game seems to work fine, but receives no input. I'm unable to move or look around.
*I can still open the console and use it.*

- Creating a blueprint from *PBPlayerCharacter* and using it as default pawn class : 
Unable to launch the game, this error comes up
![PBcharactermovement_error](https://user-images.githubusercontent.com/11683059/61877611-a464d880-aeef-11e9-927a-39552fe5bfa3.png)

*Using Unreal Engine 4.22.3, if this is of any importance...*

**Comment by mastercoms** [comment]
Make sure you've set your launch profile to build the game.

**Comment by axel37** [comment]
I am sorry but I'm not quite sure of what you're asking me.
However, after changing some launch settings, this happened :
![PBcharactermovement_plugin_properly_installed](https://user-images.githubusercontent.com/11683059/61902819-43ef8e80-af23-11e9-8b2b-6282340e357b.png)
*That might be related to the previous issue, or me changing the wrong settings*

**Comment by mastercoms** [comment]
How are you launching the game? You need to make sure that in your launch settings, you have the "Build" step checked.

**Comment by mastercoms** [comment]
How are you launching the game? You need to make sure that in your launch settings, you have the "Build" step checked.

https://docs.unrealengine.com/en-US/Engine/Deployment/ProjectLauncher/index.html

**Comment by axel37** [comment]
At first, I was launching it from the toolbar. I also used the project launcher to create a new profile *(and to make sure the build step was checked)*. However, I am still getting the same error.
[The log](https://github.com/ProjectBorealis/PBCharacterMovement/files/3438088/ProjectLauncher.log) might help.
Also, here's a screenshot of the project launcher after *"completion"*
![image](https://user-images.githubusercontent.com/11683059/61993587-51fdf600-b06e-11e9-8cce-b243008bc1cc.png)

**Comment by mastercoms** [comment]
Will try to check this out soon, but we have limited time so it might take a bit.

**Comment by mastercoms** [comment]
Is this a C++ project, or a Blueprint project? If it is a C++ project, you may have to add PBCharacterMovement as a dependency in your Build.cs.

**Comment by axel37** [comment]
It is a Blueprint project.

**Comment by mastercoms** [comment]
@axel37 Could you try converting it to a C++ project?

**Comment by SpawnZlive** [comment]
> 
> 
> @axel37 Could you try converting it to a C++ project?

I was also having this issue and converting to a C++ project fixed it.
Thanks!
