### ISSUE TITLE
Everything work great but is there any way to add sprinting with registered sounds (like the sprint sounds in PBPFootsteps)

### ISSUE THREAD

**Issue by Mistamack713** [ProjectBorealis/PBCharacterMovement#52]
All I want to do is add sprinting that works like its part of the plugin I know what it says in the redistribute note but I just want to know if theres any real way to do this

**Comment by mastercoms** [comment]
Yes, as long as you are moving at sprint speed, then sprint sounds will play, as configured in MoveStepSounds.
